### ISSUE TITLE
MySQL no saves

### ISSUE THREAD

**Issue by Simul4kruM** [brunyman/MPDB#109]
Hey
I installed this plugin on 2 of my backend servers (Paper 1.19.4). I set up MySQL-Data and did define, what data I'd like to synchronize. On server startup, the tables have been created, so a data connection to MySQL has been established. I got the message in console about which data are enabled for sync.
If I now log on server, I can't do anything, it just says sync in progress. Even if I try to /mpdb importData in console, the data import seems to start, but it is stuck at 1/431 without any further information.

Many other plugins like LuckPerms, Jobs, Logger...... are working fine.

What could I do to get data saved into created tables?

**Comment by brunyman** [comment]
Hi,

Please share a log, just join for 30 sec and then disconnect and after that run the import command. I would like to see if there something useful on the logs to identify the issue.

**Comment by Simul4kruM** [comment]
Hey...
I added the complete log with player join and import and one where I did delete all stuff of other plugins...
[2023-06-18-7.log](https://github.com/brunyman/MPDB/files/11782711/2023-06-18-7.log)
[2023-06-18-7mysqlbridge.log](https://github.com/brunyman/MPDB/files/11782712/2023-06-18-7mysqlbridge.log)

**Comment by brunyman** [comment]
I did test with your paper build and modules disabled but did not manage to reproduce the issue.
 Is the server freezing when you run the import command?
What kind of mysql server you connect to?

I did not test with the set of plugins you have, can you do a simple test with only MPDB installed and see if it's the same?

**Comment by Simul4kruM** [comment]
Well, unfortunately this did not help, it seems still to be syncing a lifetime. The server does not freeze, I can move all the time but do nothing else because then there is the message, that it's still syncing.

The MySQL-Version is 5.6.33-0ubuntu0.14.04.1. It belongs to the gameserver-hoster who gives 1 table to ppl per gameserver. So I have to say that I can't change any settings there. It was not easy to find out server-version, because they even hide server informations in phpmyadmin-panel.

**Comment by brunyman** [comment]
Ok, I will do an update on the mysql driver and let you know when ready and see if that fixed it.

**Comment by brunyman** [comment]
Ok, did some changes to connection proprieties, it looks like that was the main issue when connecting to older MySQL server versions. I was using some connection optimizations with caching and older database servers did not had those.

Let me know if now everything works. Version: 4.9.2

Thanks

**Comment by Simul4kruM** [comment]
Yay, now I get message "Data sync complete!"

Thank you!
