### ISSUE TITLE
Update to 1.16.3

### ISSUE THREAD

**Issue by Florianpal1** [brunyman/MPDB#12]
In MC 1.16.3 the plugin can't load player data.

I use paper-191 and MPDB 3.34.2.

Error on server start : 
[MysqlPlayerDataBridge] Disabling Inventory, Armor and Enderchest Sync! Error: org.bukkit.craftbukkit.v1_16_R1.CraftServer

**Comment by leanderlingens** [comment]
Please update. ;)

**Comment by Dadzne94** [comment]
Good day,
it would be very nice if you could update the plugin as soon as possible. Unfortunately it has no function in 1.16.3

Thank you in advance.

**Comment by coco0325** [comment]
Plz update🙏🙏

**Comment by leanderlingens** [comment]
Thx for updating to 1.16.3.

**Comment by Dadzne94** [comment]
Thx
