### ISSUE TITLE
Wrong Color Code

### ISSUE THREAD

**Issue by coco0325** [brunyman/MPDB#44]
Hello,
I found a bug in the source code of MPDB and it causes a issue. The picture below shows the decompiled code. Seems replaceAll function replace & to a garbled instead of §.

![](https://cdn.discordapp.com/attachments/399093265468489757/853816215084466196/unknown.png)
![](https://cdn.discordapp.com/attachments/399093265468489757/853816071550402582/unknown.png)

**Comment by brunyman** [comment]
**Fixed in version 3.36.2**

Thanks for report!
