### ISSUE TITLE
Error when joining

### ISSUE THREAD

**Issue by RaceFlex** [brunyman/MPDB#74]
![Screenshot 2022-03-21 170732](https://user-images.githubusercontent.com/96721788/159302520-2b26f020-5b49-465e-8efd-ece2e0de54ed.png)
This error comes when you join the server

**Comment by brunyman** [comment]
This should be fixed in version 4.4.0, I will need a confirmation

**Comment by RaceFlex** [comment]
It looks like it's working now, thank you
