### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by RaceFlex** [brunyman/MPDB#75]
In the plugin version 4.0.0 the armor is not synced if a player takes armor and puts it on and then goes offline and you then look at the armor with /mpdb armor <name> and the player then comes online, he still has it Armor, and yes I know I'm using an outdated version that's because the latest one isn't compatible with 1.17.1, by the way I've already written an article about this (https://github.com/brunyman/MPDB/issues/74 )

**Comment by brunyman** [comment]
Fixed in version 4.4.1, please confirm

**Comment by RaceFlex** [comment]
Cool great works now thank you very much

**Comment by PadowYT2** [comment]
Close the issue?
