### ISSUE TITLE
Offline Inventory

### ISSUE THREAD

**Issue by Lorias-Jak** [brunyman/MPDB#79]
Hey hey,

I am considering getting the plugin for our server. The question I have is, can I also open and edit the inventories of offline players?

**Comment by brunyman** [comment]
Yes, with this command for online and offline players:
**/mpdb inv <name>** - MPDB.moderator - Open and edit a player's inventory.

With the limitation that if you edit the inventory of a player that is offline on that server but he is online on another server that is in sync changes will not apply as you will need to edit the inventory where the player is online
