### ISSUE TITLE
Error with ProtocolLib and eco

### ISSUE THREAD

**Issue by AlexanderMoebius** [brunyman/MPDB#85]
Detailed issue report can be seen here: https://github.com/Auxilor/eco/issues/185

**Comment by brunyman** [comment]
I replied there, doesn't look like a bug on my end. What happens before the error takes place? Just for context

**Comment by AlexanderMoebius** [comment]
I answered in the other thread.
Probably a compatibility problem with ProtocolLib v4 vs v5.
